export const SHOW_LOADING = "SHOW_LOADING";
export const HIDE_LOADING = "HIDE_LOADING";

export const GET_CELL_GROUPS_SUCCESS = "GET_CELL_GROUPS_SUCCESS";
export const CELL_GROUP_ERROR = "CELL_GROUP_ERROR";
