export const API_CALL_BEGAN = "API_CALL_BEGAN";

export const AUTH_REQUESTED = "AUTH_REQUESTED";
export const AUTH_REGISTER_SUCCESS = "AUTH_REGISTER_SUCCESS";
export const AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS";
export const AUTH_LOAD_USER = "AUTH_LOAD_USER";
export const AUTH_ERROR = "AUTH_ERROR";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const CELL_GROUPS_REQUESTED = "CELL_GROUPS_REQUESTED";
export const CELL_GROUP_ERROR = "CELL_GROUP_ERROR";
export const GET_CELL_GROUPS_SUCCESS = "GET_CELL_GROUPS_SUCCESS";

export const PROFILE_REQUESTED = "PROFILE_REQUESTED";
export const GET_PROFILE_SUCCESS = "GET_PROFILE_SUCCESS";
export const SAVE_PROFILE_SUCCESS = "SAVE_PROFILE_SUCCESS";
export const PROFILE_ERROR = "PROFILE_ERROR";

export const USER_REQUESTED = "USER_REQUESTED";
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";
export const GET_SINGLE_USER_SUCCESS = "GET_SINGLE_USER_SUCCESS";
export const USER_ERROR = "USER_ERROR";
